spring.application.name=srpingbootcoredemo2
# paymentGateway.type=RazonPay
# paymentGateway.retryCnt=10
payment-properties.type=RazonPay
payment-properties.retry-count=10
payment-properties.enabled=true
payment-properties.timeout=3000
